# Generated by Django 4.0.1 on 2022-01-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NftProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitterLink', models.URLField(blank=True, null=True)),
                ('discordLink', models.URLField(blank=True, null=True)),
                ('homepageLink', models.URLField(blank=True, null=True)),
                ('plusLink1', models.URLField(blank=True, null=True)),
                ('plusLink2', models.URLField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
